spring:
  datasource:
    password: '@Teste123'
    username: 'teste'
    url: jdbc:mysql://localhost:3306/alura

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
